# workflow 名称
name: Weather

on:   # 触发条件
  push:
    branches: [ main ] # push代码后触发
  workflow_dispatch: # GitHub 页面上手工触发
  schedule:
    - cron: 0 23 * * *  # 每天国际标准时间23点（北京时间早上7点）运行

env: # 自定义参数
  WEATHER_URL: https://tianqi.moji.com/weather/china/shanghai/pudong-new-district # 上海浦东天气url
  WEATHER_HTML: weather.html # 天气临时文件

jobs:
  Weather:
    runs-on: ubuntu-latest

    steps:
       # check out 代码
      - uses: actions/checkout@v2

      # 获取天气
      - name: The Weather Today
        id: weather
        run: | 
          curl -o ${{env.WEATHER_HTML}} ${{env.WEATHER_URL}}
          WEATHER=`sed -n '6p' ${{env.WEATHER_HTML}} | cut -d '"' -f4 | cut -d '"' -f3`
          echo "WEATHER=$WEATHER"  >> $GITHUB_ENV
          echo "::set-output name=status::success"

      # 通过 Server酱 发送微信通知
      - name: WeChat Notification
        if: steps.weather.outputs.status == 'success' && !cancelled()
        uses: yakumioto/serverchan-action@v1
        with:
          key: ${{secrets.SERVERCHAN}} # Server酱 的 token
          text: 今日天气 # 标题
          desp: ${{env.WEATHER}} # 正文

      # 删除旧的workflow
      - name: Delete Workflow Runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 30
          keep_minimum_runs: 10
